# Generated by Django 3.2.6 on 2021-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.CharField(max_length=1000000),
        ),
    ]
